tests: boardfarm: use docker_name for check_status
With https://github.com/prplfoundation/prplMesh/pull/1486, "name" was
changed to "docker_name".

The name in "check_status" was not updated, so do it now.

It fixes the following error:
Error: No such container: controller

See for example:
https://gitlab.com/prpl-foundation/prplMesh/-/jobs/625370585

Signed-off-by: Raphaël Mélotte <raphael.melotte@mind.be>