framework: test: change max ssid length
cppcheck reported an error when accessing the 'ssid' buffer:
framework/discovery_agent/test/multi_ap_agent1.cpp:40:55: error: Buffer is accessed out of bounds: apopbss_in.ap_list[i].bss_list[j].ssid [bufferAccessOutOfBounds]
            snprintf(apopbss_in.ap_list[i].bss_list[j].ssid, 9, "%s", "test_ssid");
                                                      ^
After checking the length of the buffer, it turns out it's size is 6,
not 9 (MAX_SSID_LEN).

Since the discovery agent is not useful anymore, delete it entirely.

Fixes 1 cppcheck issue of severity error.

Signed-off-by: Raphaël Mélotte <raphael.melotte@mind.be>