beerocks/bwl/dwpal: use constructor instead of memset()
beerocks::message::sRadioCapabilities sets default values for its
members, which makes the struct non-trivially-copyable.

Anyway, for classes which have a default constructor, it is better to
reset them using the default constructor rather than memset().

Therefore, replace the initialisation with memset() with an assignment.

This squelshes the following warning with GCC 9:

prplMesh/common/beerocks/bwl/dwpal/ap_wlan_hal_dwpal.cpp: In member function ‘virtual bool bwl::dwpal::ap_wlan_hal_dwpal::process_dwpal_event(char*, int, const string&)’:
prplMesh/common/beerocks/bwl/dwpal/ap_wlan_hal_dwpal.cpp:1033:78: error: ‘void* memset(void*, int, size_t)’ clearing an object of non-trivial type ‘beerocks::message::sRadioCapabilities’ {aka ‘struct beerocks::message::sRadioCapabilities’}; use assignment or value-initialization instead [-Werror=class-memaccess]
 1033 |         memset(&msg->params.capabilities, 0, sizeof(msg->params.capabilities));
      |                                                                              ^
In file included from prplMesh/common/beerocks/bwl/dwpal/../common/base_wlan_hal_types.h:13,
                 from prplMesh/common/beerocks/bwl/dwpal/../common/base_wlan_hal.h:13,
                 from prplMesh/common/beerocks/bwl/dwpal/../common/ap_wlan_hal.h:12,
                 from prplMesh/common/beerocks/bwl/dwpal/ap_wlan_hal_dwpal.h:12,
                 from prplMesh/common/beerocks/bwl/dwpal/ap_wlan_hal_dwpal.cpp:9:
prplMesh/common/beerocks/bcl/include/beerocks/bcl/beerocks_message_structs.h:35:16: note: ‘beerocks::message::sRadioCapabilities’ {aka ‘struct beerocks::message::sRadioCapabilities’} declared here
   35 | typedef struct sRadioCapabilities {
      |                ^~~~~~~~~~~~~~~~~~

Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>