tests: wrap exceptions thrown by individual tests
This way script can continue executing the next test even if one of
tests throws an exception. Also we can use assert statements inside
tests since AssertionErrors are handled and they fail the test with an
assertion failed message.

If we want to fail the test when an assertion has failed we can do the
following:

assert False, "Some assertion failed and we don't want to continue"
produces
FAIL: Some assertion failed and we don't want to continue

If we don't add an assertion failed message a generic "Assertion failed"
message will be printed, so please add messages to assert statements.

assert False
produces
FAIL: Assertion failed

But, if self.fail() is called somewhere with a proper message and we
want to end the test there without adding anything to that message you
can assert without a message.

self.fail("Something failed and we don't want to go on")
assert False
produces
FAIL: Something failed and we don't want to go on

When a test throws an unexpected run-time error the test is marked as
failed and a stack trace is printed in debug mode.

FAIL: Test failed unexpectedly: SomeRuntimeException('some error
message')
Traceback (most recent call last):
  ... stack trace showing the method
  ... which has thrown the unhandled exception
SomeRuntimeException: some error message

Please make sure to wrap all exceptions and throw only AssertionErrors
to fail the tests.

Signed-off-by: Sinan Akpolat <sinan.akpolat@lifemote.com>