controller: avoid explicit call to constructor
On the make_pair invocation, cppcheck would fail with the following error:
error: SymbolDatabase bailout; unhandled code [syntaxError]

It looks like a bug in cppcheck that I could not reproduce with a
simpler example.

Since we anyway don't need the explicit call to the constructor, use
{} to initialize the pair.

Fixes 1 cppcheck issue of severity error.

Signed-off-by: Raphaël Mélotte <raphael.melotte@mind.be>