Fix GCC 8 warnings (#4)
* common/nng/socket.cpp: SubSocker::Receive(): return correct type

This function returns a Message pointer, so return NULL instead of
false.

Fixes:
../common/nng/socket.cpp: In member function ‘std::unique_ptr<mapf::Message> mapf::SubSocket::Receive(int)’:
../common/nng/socket.cpp:226:10: error: could not convert ‘false’ from ‘bool’ to ‘std::unique_ptr<mapf::Message>’
   return false;
          ^~~~~

Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>

* ieee1905_transport_network.cpp: include sys/uio.h

writev() is declared in sys/uio.h, not in sys/socket.h.

Fixes:
../transport/ieee1905_transport/ieee1905_transport_network.cpp: In member function ‘bool mapf::Ieee1905Transport::send_packet_to_network_interface(unsigned int, mapf::Ieee1905Transport::Packet&)’:
../transport/ieee1905_transport/ieee1905_transport_network.cpp:350:13: error: ‘writev’ was not declared in this scope
     int n = writev(fd, iov, sizeof(iov)/sizeof(struct iovec));
             ^~~~~~
../transport/ieee1905_transport/ieee1905_transport_network.cpp:350:13: note: suggested alternative: ‘write’
     int n = writev(fd, iov, sizeof(iov)/sizeof(struct iovec));
             ^~~~~~
             write

Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>